name: velax
description: "A personal wardrobe application."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  drift: ^2.35.0
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.6
  image_picker: ^1.2.3
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.35.0
  build_runner: ^2.16.1

flutter:
  uses-material-design: true
